# Generated by Django 3.2.9 on 2021-12-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMarketInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'v_market_info',
                'managed': False,
            },
        ),
    ]
