# Generated by Django 3.2.9 on 2022-01-11 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'journal_balance',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('open_time', models.DateTimeField()),
                ('pct_net_profit', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'journal_transactions',
            },
        ),
        migrations.CreateModel(
            name='StockTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=5)),
                ('exchange', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('buy_point', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='journal.Tag')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.transactions')),
            ],
            options={
                'db_table': 'journal_stocktrade',
                'ordering': ['date', 'ticker'],
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('open_date', models.DateField()),
                ('open_time', models.TimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='journal.balance')),
            ],
            options={
                'db_table': 'journal_positions',
            },
        ),
    ]
