# Generated by Django 3.2.9 on 2022-01-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'journal_balance',
            },
        ),
        migrations.CreateModel(
            name='StockTrade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=5)),
                ('exchange', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('buy_point', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal_stocktrade',
                'ordering': ['date', 'ticker'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('open_time', models.DateTimeField()),
                ('pct_net_profit', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'journal_transactions',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('stock_trade', models.ManyToManyField(to='journal.StockTrade')),
            ],
        ),
        migrations.AddField(
            model_name='stocktrade',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.transactions'),
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('open_date', models.DateField()),
                ('open_time', models.TimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='journal.balance')),
            ],
            options={
                'db_table': 'journal_positions',
            },
        ),
    ]
