# Generated by Django 3.2.9 on 2021-12-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VTransactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=20)),
                ('buy_quantity', models.IntegerField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('buy_total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sell_quantity', models.IntegerField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sell_total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('trade_result', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'v_transactions',
                'managed': False,
            },
        ),
    ]
