# Generated by Django 3.2.9 on 2022-01-11 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktrade',
            options={'ordering': ['create_date', 'ticker']},
        ),
        migrations.RemoveField(
            model_name='stocktrade',
            name='date',
        ),
        migrations.AddField(
            model_name='stocktrade',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktrade',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
