# Generated by Django 3.2.9 on 2022-01-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20220111_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktrade',
            name='image',
            field=models.ImageField(blank=True, default='heart.png', null=True, upload_to=''),
        ),
    ]
