# Generated by Django 3.2.9 on 2022-01-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_stocktrade_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktrade',
            name='image',
            field=models.ImageField(blank=True, default='cycle.jpg', null=True, upload_to=''),
        ),
    ]
