# Generated by Django 3.2.9 on 2022-01-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_stocktrade_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktrade',
            name='exchange',
            field=models.CharField(choices=[('NASDAQ', 'NASDAQ'), ('GPW', 'GPW')], default='NASDAQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocktrade',
            name='image',
            field=models.ImageField(blank=True, default='cycle.jpg', null=True, upload_to='', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='stocktrade',
            name='tags',
            field=models.ManyToManyField(to='journal.Tag', verbose_name='Tagi'),
        ),
        migrations.AlterField(
            model_name='stocktrade',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.transactions', verbose_name='Opis'),
        ),
    ]
