# Generated by Django 3.2.9 on 2022-01-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20220120_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktrade',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='stocktrade',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.transactions'),
        ),
    ]
