tickers_list = [
    'NYSE:AA','NASDAQ:ALGN','NASDAQ:ATER','NASDAQ:BEEM','NASDAQ:CODX','NYSE:COTY','NASDAQ:CSCO','NYSE:DE',
    'NYSE:FLR','NASDAQ:GEVO','NYSE:HPQ','NYSE:MP','NYSE:NTR','NASDAQ:NVAX','NYSE:PCG','NASDAQ:PSEC','NYSE:RIG',
    'NYSE:SLB','NASDAQ:SNDL','NASDAQ:SOFI','NYSE:VAC','NYSE:X','NYSE:ZIM','NASDAQ:FB','NASDAQ:AMZN','NASDAQ:NFLX','CAPITALCOM:GOOG','NASDAQ:MSFT','NASDAQ:AAPL','NASDAQ:TSLA',
    'NASDAQ:NVDA','NASDAQ:AMD','NYSE:FLR','NYSE:SLB','NYSE:COTY','NYSE:HPQ','NYSE:PCG','NYSE:ZIM'
]

len(tickers_list)
# tickers_list = [
#     'GPW:ALE','GPW:LWB','GPW:XTB','GPW:JSW','GPW:PKO','GPW:PEO','GPW:PGN','GPW:PZU','GPW:PKN','GPW:LVC','GPW:KGH','GPW:BMC','GPW:ENA','GPW:ALR','TVC:NDX','NASDAQ:FB','NASDAQ:DLTR','NASDAQ:MSFT','NYSE:IONQ','NASDAQ:TSLA','NASDAQ:AAPL','NASDAQ:DWAC','NYSE:AMC','NASDAQ:MU','NYSE:RBLX','NASDAQ:APPN','NYSE:MP','NASDAQ:AFRM','NASDAQ:MTTR','NASDAQ:CAR','NASDAQ:TSP','NASDAQ:ZS','NASDAQ:ABNB','NASDAQ:ADSK','NYSE:SNOW','NASDAQ:LCID','NASDAQ:NVDA','NASDAQ:RIVN','NYSE:FCX','NYSE:KL','NYSE:FNV','AMEX:PHYS','NYSE:NEM','NYSE:EDR','NYSE:CCJ','NYSE:BROS','NASDAQ:ARCB','NASDAQ:QCOM','NYSE:U','NYSE:F','NASDAQ:TTD','NASDAQ:ALGM','NASDAQ:CCMP','NASDAQ:AMD','NASDAQ:AMZN','NASDAQ:WFRD','NASDAQ:PLBY','NASDAQ:PUBM','NYSE:ANET','NYSE:HD','NYSE:NEWR','NYSE:KBH','NASDAQ:GDYN','NYSE:ZIM','NASDAQ:BRLT','NYSE:ONON','NYSE:SPCE','NASDAQ:ENPH','NASDAQ:DDOG','NYSE:M','NASDAQ:APP','NYSE:PSTG','NYSE:LEN','NASDAQ:OLPX','NYSE:ORCL','NASDAQ:MRVL','NASDAQ:AMBA','NASDAQ:LWLG','NYSE:GXO','NASDAQ:SOFI','NYSE:LC','NASDAQ:BLNK','NYSE:WOLF','NASDAQ:GT','NYSE:HRI','NASDAQ:MDB','NASDAQ:GFS','NASDAQ:PERI','NASDAQ:ON','NYSE:LAC','NYSE:SI','NASDAQ:MRAM','NASDAQ:UPST','NYSE:NET','NASDAQ:ETSY','NASDAQ:CFLT','NYSE:DOCN','NASDAQ:COIN','NYSE:SQ','NASDAQ:SLDP','NASDAQ:ENVX','NASDAQ:ISPC','NASDAQ:SITM','NYSE:PATH','NASDAQ:EXTR','NASDAQ:NVAX','NASDAQ:TRUP','NASDAQ:PTLO','NASDAQ:AMEH','NASDAQ:CCXI','AMEX:TRT','NYSE:GEL','NASDAQ:PLUG','NASDAQ:SKIN','NASDAQ:CYBR','NYSE:XPOF','NASDAQ:ARQQ','NASDAQ:HUT','NYSE:SAIL','NYSE:CARS','NYSE:AKA','NASDAQ:GDRX','NYSE:MEG','NASDAQ:PETZ','NYSE:SHOP','NASDAQ:BRP','NYSE:AGTI','NASDAQ:AMPL','NASDAQ:ZM','NASDAQ:SNPO','NYSE:SKT','NYSE:ZIP','NASDAQ:AEHR','NYSE:PLTR','NASDAQ:FCEL','NASDAQ:LOVE','NASDAQ:GOEV','NASDAQ:TEAM','NASDAQ:SGH','NYSE:KKR','NASDAQ:ARBK','NYSE:WLL','NYSE:FSR','NYSE:AMRC','NYSE:DEN','NASDAQ:LSCC','NASDAQ:SLAB','NASDAQ:PRFT','NYSE:GOLF','NYSE:WBX','NYSE:NUE','NASDAQ:NTCT','NASDAQ:RILY','NYSE:NKE','NYSE:DKS','NASDAQ:KRUS','NYSE:HPQ','NYSE:BABA','NASDAQ:LRCX','NYSE:PLD','NASDAQ:TTGT','NYSE:LYV','NYSE:DDS','NYSE:VRTV','NYSE:NTR','NYSE:BRK.B','NASDAQ:SIMO','NASDAQ:SHYF','NYSE:PAG','NASDAQ:TER','NASDAQ:POOL','NYSE:TREX','NYSE:IT','NYSE:CF','NASDAQ:AUR','NASDAQ:QFIN','NYSE:GM','NASDAQ:BFRI','NASDAQ:MXL','NYSE:RFP','NYSE:SWN','NASDAQ:HLIT','NYSE:SHW','NYSE:ATKR','NASDAQ:CSCO','NASDAQ:COST','NYSE:KO','NASDAQ:YELL','NYSE:PFE','NYSE:FLR','NYSE:CIVI','NASDAQ:PLAB','NASDAQ:SYNA','NYSE:CUBI','NYSE:IAG','NASDAQ:SOPA'
# ]

string1 = "s{} = security('{}', 'D', customFunc())"

for i, elem in enumerate(tickers_list):
    print(string1.format(i + 1, elem))

string2 = "src_label := s{} ? src_label + '{}\\n' : src_label"

for i, elem in enumerate(tickers_list):
    print(string2.format(i + 1, elem))

